### ISSUE TITLE
HyperGBM run on K8s when set the limits of cpu and memory

### ISSUE THREAD

**Issue by SonixLegend** [DataCanvasIO/HyperGBM#93]
This template is for miscellaneous issues not covered by the other issue categories.

When we ran HyperGBM on k8s, if the resources of cpu and memory were far lower than the whole resources on the machine after has setted the k8s resource limits, the HyperGBM would trigger the earlystop with timeout error. We found the k8s pod can watch all cpu even if it has the resource limits.

**Comment by oaksharks** [comment]
Hi SonixLegend, 
If HyperGBM run slowly in a docker container when limit CPU cores, this is usually caused by the algorithmic framework(XGBoost, LightGBM, etc. ) used by HyperGBM not realizing that the current container is restricted to CPUs and has opened too many threads.

For example, the host machine has 40 CPU cores and the container is limited to use 4 of them. When the algorithm framework  starts training, it recognized that 40 CPU cores are available then start 40 threads by default. However, only 4 cores are actually available, which leads to very low performance.

You can set the environment variables of the container `OMP_NUM_THREADS=4` to tell the algorithm to only open 4 threads. 

Hope this will help.

References:
- https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
- https://stackoverflow.com/questions/48269248/limiting-the-number-of-threads-used-by-xgboost

**Comment by SonixLegend** [comment]
You are right. We have tried it. That's ok.
